### ISSUE TITLE
where is the section that inferences the sub topics in layer 1?

### ISSUE THREAD

**Issue by bhomass** [ethanhezhao/WEDTM#3]
Hi Dr He (do you know we have the same last name)
I am going thru your paper and code. It runs from beg to end with no problem. In WEDTM.m, I am sure where you implemented the main part of the paper which is section 4. Inference, where you used 2 CRT and 1 Normal distribution to sample beta, alpha and w. 

I see sampling done for beta, and possibly w, but I don't see alpha being sampled.

Thank you
Bruce

**Comment by ethanhezhao** [comment]
Hi, alpha is sampled by Eq. (3) in the paper and its implementation is at Line 84 in 'sample_beta.m'.

**Comment by bhomass** [comment]
Thank you. I found it. what are all these eqn numbers referring to? all the way up to eqn 15. there is not that many eqns in the paper.

**Comment by ethanhezhao** [comment]
Hi, the details are in the supplementary material.
